modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU LGPL 3.0"
issueTrackerURL = "https://github.com/ArkTechMC/RainimatorMod/issues"
[[mods]]
modId = "rainimator"
version = "${version}"
displayName = "Rainimator Mod"
logoFile = "logo.jpg"
authors = "IAFEnvoy"
description = '''
Rainimator Minecraft Animation mod. @Rainimator @Rainolaguer
'''
[[dependencies.rainimator]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.rainimator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
[[dependencies.rainimator]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"